---
# tasks file for install-tools
- name: "Installing additional tools" 
  become: true 
  become_method: sudo 
  package: 
    name: "{{ item }}" 
    state: present 
  loop: 
    - pspy 
    - peass 
    - chisel 
    - gobuster
    - xclip 
    - feh
