---
# tasks file for install-tools
- name: "Installing additional tools" 
  become: true 
  become_method: sudo 
  - name: "Installing {{ item }}" 
    package: 
      name: "{{ item }}" 
      state: present 
    loop: 
      - pspy 
      - peass 
      - chisel 
      - xclip 
      - feh
