---
# tasks file for configure-zsh
- name: "Copy .zshrc" 
  copy: 
    src: "{{ role_path }}/files/.zshrc" 
    dest: "/home/{{ ansible_user_id }}" 
    owner: "{{ ansible_user_id }}" 
    group: "{{ ansible_user_id }}" 
