--- 
- name: "Customizing Kali Linux" 
  hosts: localhost 
  connection: local 
    roles:
    - role: "roles/install-tools" 
    - role: "roles/configure-zsh" 
    - role: "roles/configure-i3wm"
    - role: "roles/configure-rofi" 
    - role: "roles/configure-tmux" 
    - role: "roles/configure-docker" 
    - role: "roles/configure-browser" 
