---
# tasks file for configure-tmux
- name: "Installing tmux terminal multiplexer" 
  apt: 
    name: tmux 
    state: present 
  become: true 
  become_method: sudo 
- name: "Copying tmux config to home directory" 
  copy: 
    src: "{{ role_path }}/files/.tmux.conf" 
    dest: "/home/{{ ansible_user_id }}" 
    owner: "{{ ansible_user_id }}" 
    group: "{{ ansible_user_id }}" 
- name: "Running source on .tmux.conf" 
  shell: tmux source-file ~/.tmux.conf
