---
# tasks file for configure-i3wm
- name: "Installing i3 window manager" 
  apt: 
    name: i3 
    state: present 
  become: true 
  become_method: sudo 
- name: "Creating .config file" 
  file: 
    path: "/home/{{ ansible_user_id }}/.config" 
    state: "directory" 
    mode: 0750
    owner: "{{ ansible_user_id }}"   
    group: "{{ ansible_user_id }}"  
- name: "Creating i3 directory in .config" 
  file: 
    path: "/home/{{ ansible_user_id }}/.config/i3" 
    state: "directory" 
    mode: 0750
    owner: "{{ ansible_user_id }}"  
    group: "{{ ansible_user_id }}"   
- name: "Copying i3 config file to ~/.config/i3" 
  copy: 
    src: "{{ role_path }}/files/config" 
    dest: "/home/{{ ansible_user_id }}/.config/i3/config" 
    mode: 0600 
    owner: "{{ ansible_user_id }}"  
    group: "{{ ansible_user_id }}"  
- name: "Copying wallpaper" 
  copy: 
    src: "{{ role_path }}/files/wallpaper.png" 
    dest: "/home/{{ ansible_user_id }}/Pictures/wallpaper.png" 
    mode: 0644 
    owner: "{{ ansible_user_id }}" 
    group: "{{ ansible_user_id }}" 
