---
# tasks file for configure-browser
- name: "Updating FireFox policies" 
  template: 
    src: "templates/policies.json.j2" 
    dest: "/usr/share/firefox-esr/distribution/policies.json" 
  become: true 
  become_method: sudo 
